insert into public.crews (
  slug, owner_name, owner_handle, name, thesis, trading, language,
  market_hours, voice_preference, capacity, live_count, access_mode,
  track_record, age_label
)
values
  ('night-shift', 'Marisol Devane', 'marisolonchain', 'Night Shift',
   'Fresh pools after the New York close. Every call ships with a contract and an exit.',
   'Memecoins', 'English', 'Americas', 'Voice daily', 8, 4, 'One question',
   'Wallets public since week one', '11 weeks together'),
  ('frogwater', 'Teodor Vasilj', 'teovasilj', 'Frogwater',
   'Slow entries on small caps. Liquidity, holder spread and an invalidation, or it does not get posted.',
   'Memecoins', 'English', 'Europe', 'Voice sometimes', 8, 2, 'One question',
   'Call history open to members', '5 months together'),
  ('second-wave', 'Amaka Oyelaran', 'amakaoye', 'Second Wave',
   'Abandoned tickers with a community still awake. We read the ownership change before the chart.',
   'Memecoins', 'English', 'Around the clock', 'Voice daily', 8, 5, 'Invite review',
   'Six theses running', '3 months together'),
  ('salt-flats', 'Ruthie Kohler', 'ruthiekohler', 'Salt Flats',
   'One position at a time, held for weeks. Nobody here is watching a five minute candle.',
   'Perps', 'English', 'Americas', 'Text only', 8, 1, 'Open',
   'Average hold 19 days', '8 months together'),
  ('la-tarde', 'Iker Balaguer', 'ikerbalaguer', 'La Tarde',
   'Spanish speaking room, afternoons in Madrid. Charts out loud, no signal spam.',
   'Memecoins', 'Espanol', 'Europe', 'Voice daily', 8, 3, 'Waitlist',
   'Wallets public since week one', '14 weeks together'),
  ('paper-route', 'Deshaun Priolo', 'deshaunp', 'Paper Route',
   'Everyone starts with a paper book for two weeks. Post the sheet, then post the trade.',
   'Day trading', 'English', 'Around the clock', 'Voice sometimes', 8, 2, 'Open',
   'Beginners welcome, no fee', '6 weeks together'),
  ('nine-lives', 'Wen Jia Loh', 'wenjialoh', 'Nine Lives',
   'Launch snipes with hard rules. Two misses in a row and you sit out the week.',
   'Memecoins', 'English', 'Asia', 'Voice daily', 8, 6, 'Invite review',
   'Rules pinned and enforced', '9 weeks together'),
  ('kervan', 'Deniz Akaydin', 'denizakaydin', 'Kervan',
   'Turkish room built on one weekly thesis. We argue it on Sunday and trade it all week.',
   'Perps', 'Turkce', 'Europe', 'Voice sometimes', 8, 1, 'One question',
   'One thesis a week, written down', '4 months together'),
  ('warung', 'Rangga Setiawan', 'ranggaseti', 'Warung',
   'Jakarta hours, small size, long conversations. Nobody is trying to sell you a course.',
   'Day trading', 'Bahasa', 'Asia', 'Text only', 8, 2, 'Open',
   'Call history open to members', '7 weeks together'),
  ('les-halles', 'Camille Rouvier', 'camillerouvier', 'Les Halles',
   'French room for mid caps only. If it launched today it is not on the table.',
   'Perps', 'Francais', 'Europe', 'Voice sometimes', 8, 0, 'Waitlist',
   'Average hold 26 days', '6 months together'),
  ('cold-open', 'Hina Matsuura', 'hinamatsuura', 'Cold Open',
   'Asia morning rotation. Two hours of voice, then everyone goes back to a day job.',
   'Day trading', 'English', 'Asia', 'Voice daily', 8, 4, 'Waitlist',
   'Wallets public since week one', '12 weeks together'),
  ('the-bakery', 'Oskar Lindqvist', 'oskarlindq', 'The Bakery',
   'Launch snipes on a shared checklist. Contract, mint authority, top ten holders, then size.',
   'Memecoins', 'English', 'Around the clock', 'Voice daily', 8, 7, 'Invite review',
   'Checklist pinned and enforced', '5 months together')
on conflict (slug) do nothing;
