import { useEffect, useMemo, useRef, useState } from "react";
import { AnimatePresence, motion } from "motion/react";
import { ArrowRight, Check, ChatCircleDots, Clock, Globe, Handshake, MagnifyingGlass, PaperPlaneTilt, SpinnerGap, UserCirclePlus, UsersThree, X } from "@phosphor-icons/react";
import { Button, Mark } from "./ui.jsx";
import { createIntroduction, decideConnection, discoverPeople, loadConnections, loadConversations, loadDirectMessages, loadIntroductions, openConversation, requestConnection, sendDirectMessage, subscribeToConnections, subscribeToDirectMessages } from "../services/social.js";

function Avatar({ person, size = 48 }) {
  return person.avatar_url ? <img className="fnf-avatar" src={person.avatar_url} alt="" style={{ width: size, height: size }} /> : <Mark name={person.display_name || "FNF"} size={size} />;
}

function reasons(person) {
  const items = [];
  if (person.mutual_crews) items.push(`${person.mutual_crews} mutual ${Number(person.mutual_crews) === 1 ? "room" : "rooms"}`);
  if (person.language) items.push(`Speaks ${person.language}`);
  if (person.market_hours) items.push(`Active ${person.market_hours}`);
  if (person.communication_style) items.push(person.communication_style);
  return items.slice(0, 3);
}

export function PeopleNetwork({ online = [], onMessage }) {
  const [people, setPeople] = useState([]); const [connections, setConnections] = useState([]); const [introductions, setIntroductions] = useState([]);
  const [query, setQuery] = useState(""); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(""); const [error, setError] = useState("");
  const [introOpen, setIntroOpen] = useState(false); const [introA, setIntroA] = useState(""); const [introB, setIntroB] = useState(""); const [introNote, setIntroNote] = useState("");
  const onlineIds = useMemo(() => new Set(online.map((item) => item.id)), [online]);
  const refresh = async (search = query) => { setLoading(true); try { const [nextPeople, nextConnections, nextIntros] = await Promise.all([discoverPeople(search), loadConnections(), loadIntroductions()]); setPeople(nextPeople); setConnections(nextConnections); setIntroductions(nextIntros); } catch (cause) { setError(cause.message); } finally { setLoading(false); } };
  useEffect(() => { const timer = window.setTimeout(() => refresh(query), 220); return () => window.clearTimeout(timer); }, [query]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => subscribeToConnections(() => refresh(query)), [query]); // eslint-disable-line react-hooks/exhaustive-deps
  const incoming = connections.filter((item) => item.status === "pending" && item.direction === "incoming");
  const accepted = connections.filter((item) => item.status === "accepted");
  const connect = async (id) => { setBusy(id); setError(""); try { await requestConnection(id); await refresh(); } catch (cause) { setError(cause.message); } finally { setBusy(""); } };
  const decide = async (item, choice) => { setBusy(item.connection_id); try { await decideConnection(item.connection_id, choice); await refresh(); } catch (cause) { setError(cause.message); } finally { setBusy(""); } };
  const message = async (id) => { setBusy(id); try { onMessage(await openConversation(id)); } catch (cause) { setError(cause.message); } finally { setBusy(""); } };
  const introduce = async (event) => { event.preventDefault(); setBusy("intro"); try { await createIntroduction(introA, introB, introNote); setIntroOpen(false); setIntroA(""); setIntroB(""); setIntroNote(""); await refresh(); } catch (cause) { setError(cause.message); } finally { setBusy(""); } };

  return <div className="app-page social-page"><header className="app-page-title app-page-title--action"><div><span>PEOPLE / NOT FOLLOWERS</span><h1>Your trading network.</h1><p>Compatibility, mutual rooms and thoughtful introductions. No audience scores.</p></div>{accepted.length >= 2 && <Button onClick={() => setIntroOpen(true)}><Handshake />Make an introduction</Button>}</header>
    {error && <div className="app-alert">{error}<button onClick={() => setError("")}>Dismiss</button></div>}
    <div className="social-presence-strip"><span><i />{online.length} online now</span>{online.slice(0, 7).map((person) => <div key={person.id}>{person.avatarUrl ? <img src={person.avatarUrl} alt="" /> : <Mark name={person.displayName} size={30} />}<small>{person.displayName}</small></div>)}{!online.length && <p>Your network will appear here as people come online.</p>}</div>
    {incoming.length > 0 && <section className="social-section"><header><span>WAITING FOR YOU</span><h2>Connection requests.</h2></header><div className="connection-requests">{incoming.map((person) => <article key={person.connection_id}><Avatar person={person} /><div><strong>{person.display_name}</strong><span>@{person.handle} · {person.trading}</span></div><Button size="sm" variant="secondary" onClick={() => decide(person, "declined")}><X />Pass</Button><Button size="sm" onClick={() => decide(person, "accepted")}><Check />Connect</Button></article>)}</div></section>}
    <section className="social-section"><header className="social-section__search"><div><span>COMPATIBILITY DISCOVERY</span><h2>People you should meet.</h2></div><label><MagnifyingGlass /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search people or bios" /></label></header>
      {loading ? <div className="app-loading"><SpinnerGap className="animate-spin" />Finding compatible people…</div> : <div className="people-grid">{people.map((person) => <article className="person-card" key={person.id}><header><Avatar person={person} size={56} /><div className="person-card__match"><strong>{person.match_score}%</strong><span>fit</span></div>{onlineIds.has(person.id) && <i className="person-online">online</i>}</header><h3>{person.display_name}</h3><p className="person-handle">@{person.handle}{person.location ? ` · ${person.location}` : ""}</p><p className="person-bio">{person.bio || "Building a smaller, sharper circle."}</p><div className="person-reasons">{reasons(person).map((reason) => <span key={reason}>{reason}</span>)}</div><footer>{person.connection_status === "accepted" ? <Button onClick={() => message(person.id)} disabled={busy === person.id}><ChatCircleDots />Message</Button> : person.connection_status === "pending" ? <Button variant="secondary" disabled><Clock />Request sent</Button> : <Button onClick={() => connect(person.id)} disabled={busy === person.id}>{busy === person.id ? <SpinnerGap className="animate-spin" /> : <UserCirclePlus />}Connect</Button>}<span>{person.experience_level}</span></footer></article>)}</div>}
    </section>
    <section className="social-section social-section--split"><div><header><span>YOUR CIRCLE</span><h2>Connections.</h2></header>{accepted.length ? <div className="connection-list">{accepted.map((person) => <button key={person.connection_id} onClick={() => message(person.user_id)}><Avatar person={person} size={40} /><span><strong>{person.display_name}</strong><small>@{person.handle} · {onlineIds.has(person.user_id) ? "online" : "offline"}</small></span><ArrowRight /></button>)}</div> : <div className="market-blank"><UsersThree /><strong>Your circle starts here.</strong><span>Connections are mutual. Nobody can follow you silently.</span></div>}</div><div><header><span>INTRODUCED BY PEOPLE YOU TRUST</span><h2>Introductions.</h2></header>{introductions.length ? <div className="intro-list">{introductions.map((intro) => <article key={intro.id}><Avatar person={{ display_name: intro.other_name, avatar_url: intro.other_avatar_url }} size={42} /><div><strong>{intro.other_name}</strong><span>@{intro.other_handle} · via {intro.introducer_name}</span><p>“{intro.note}”</p></div><Button size="sm" onClick={() => connect(intro.other_user_id)}>Connect</Button></article>)}</div> : <div className="market-blank"><Handshake /><strong>No introductions yet.</strong><span>The best new connection starts with a reason from someone you know.</span></div>}</div></section>
    <AnimatePresence>{introOpen && <motion.div className="social-modal" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><motion.form initial={{ scale: .97, y: 16 }} animate={{ scale: 1, y: 0 }} onSubmit={introduce}><header><div><span>FNF INTRODUCTION</span><h2>Connect two people.</h2></div><button type="button" onClick={() => setIntroOpen(false)}><X /></button></header><p>Give both people a real reason to meet. This is not a referral blast.</p><label><span>First person</span><select value={introA} onChange={(event) => setIntroA(event.target.value)} required><option value="">Choose a connection</option>{accepted.map((item) => <option key={item.user_id} value={item.user_id}>{item.display_name}</option>)}</select></label><label><span>Second person</span><select value={introB} onChange={(event) => setIntroB(event.target.value)} required><option value="">Choose a different connection</option>{accepted.filter((item) => item.user_id !== introA).map((item) => <option key={item.user_id} value={item.user_id}>{item.display_name}</option>)}</select></label><label><span>Why should they meet?</span><textarea value={introNote} onChange={(event) => setIntroNote(event.target.value)} minLength="4" maxLength="280" rows="4" placeholder="You both trade Solana memes during European hours and prefer voice rooms." required /></label><Button type="submit" disabled={busy === "intro"}>{busy === "intro" ? <SpinnerGap className="animate-spin" /> : <Handshake />}Send introduction</Button></motion.form></motion.div>}</AnimatePresence>
  </div>;
}

export function DirectMessages({ session, initialConversation }) {
  const [conversations, setConversations] = useState([]); const [active, setActive] = useState(initialConversation || null); const [messages, setMessages] = useState([]); const [body, setBody] = useState(""); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const endRef = useRef(null);
  const refreshConversations = () => loadConversations().then((items) => { setConversations(items); if (!active && items[0]) setActive(items[0].conversation_id); }).catch((cause) => setError(cause.message));
  useEffect(() => { refreshConversations().finally(() => setLoading(false)); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { if (!initialConversation) return; setActive(initialConversation); }, [initialConversation]);
  useEffect(() => {
    if (!active) { setMessages([]); return undefined; }
    let alive = true; loadDirectMessages(active).then((items) => alive && setMessages(items)).catch((cause) => setError(cause.message));
    const stop = subscribeToDirectMessages(active, (item) => setMessages((current) => current.some((message) => message.id === item.id) ? current : [...current, item]));
    return () => { alive = false; stop(); };
  }, [active]);
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: "smooth" }); }, [messages]);
  const submit = async (event) => { event.preventDefault(); const text = body.trim(); if (!text || !active) return; setBody(""); try { await sendDirectMessage(active, text); refreshConversations(); } catch (cause) { setBody(text); setError(cause.message); } };
  const person = conversations.find((item) => item.conversation_id === active);
  return <div className="app-page"><header className="app-page-title"><span>CONSENT-BASED DMS</span><h1>Messages.</h1><p>Only mutual connections can enter your inbox.</p></header>{error && <div className="app-alert">{error}</div>}<div className="dm-shell"><aside><header><strong>Conversations</strong><span>{conversations.length}</span></header>{loading && <SpinnerGap className="animate-spin" />}{conversations.map((item) => <button key={item.conversation_id} className={active === item.conversation_id ? "active" : ""} onClick={() => setActive(item.conversation_id)}><Avatar person={item} size={42} /><span><strong>{item.display_name}</strong><small>{item.last_body}</small></span>{Number(item.unread) > 0 && <b>{item.unread}</b>}</button>)}{!loading && !conversations.length && <p>Connect with someone before starting a private conversation.</p>}</aside><section className="dm-thread">{person ? <><header><Avatar person={person} size={40} /><div><strong>{person.display_name}</strong><span>@{person.handle}</span></div></header><div className="dm-messages">{messages.map((message) => <article className={message.sender_id === session.user.id ? "mine" : ""} key={message.id}><div><p>{message.body}</p><time>{new Date(message.created_at).toLocaleTimeString([], { hour: "numeric", minute: "2-digit" })}</time></div></article>)}<div ref={endRef} /></div><form onSubmit={submit}><textarea value={body} onChange={(event) => setBody(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.shiftKey) submit(event); }} rows="1" placeholder={`Message ${person.display_name}`} maxLength="2000" /><button disabled={!body.trim()}><PaperPlaneTilt />Send</button></form></> : <div className="dm-empty"><ChatCircleDots /><strong>Private by design.</strong><span>Select a mutual connection to start talking.</span></div>}</section></div></div>;
}
