/* ---------------------------------------------------------------
   Image slots.
   Each entry has the final path the site should ship with and a
   temporary source. Drop the real file at `path`, then flip `src`
   to that path. Nothing else needs to change.
--------------------------------------------------------------- */
export const IMG = {
  hero: {
    path: "/assets/fnf-degen-hero.png",
    src: "/assets/fnf-degen-hero.png",
    w: 1672,
    h: 941,
    alt: "A chaotic late-night trading crew around a laptop, surrounded by ripped paper and original memecoin stickers.",
  },
  desk: {
    path: "/assets/fnf-degen-board.png",
    src: "/assets/fnf-degen-board.png",
    w: 1448,
    h: 1086,
    alt: "A messy memecoin research wall covered with torn screenshots, charts, tape, and original monster doodles.",
  },
  hands: {
    path: "/assets/fnf-degen-wallet.png",
    src: "/assets/fnf-degen-wallet.png",
    w: 1448,
    h: 1086,
    alt: "A phone with blurred wallet history held above a dirty table of receipts, tape, and memecoin sketches.",
  },
  walk: {
    path: "/assets/fnf-degen-hero.png",
    src: "/assets/fnf-degen-hero.png",
    w: 1672,
    h: 941,
    alt: "A late-night memecoin crew watching charts together in a messy bedroom.",
  },
  ledger: {
    path: "/assets/fnf-degen-board.png",
    src: "/assets/fnf-degen-board.png",
    w: 1448,
    h: 1086,
    alt: "A torn-paper trading evidence board with abstract charts, receipts, and original degen mascot stickers.",
  },
  process: {
    path: "/assets/fnf-degen-process.png",
    src: "/assets/fnf-degen-process.png",
    w: 1672,
    h: 941,
    alt: "A ripped-paper triptych showing a preferences card, a crew shortlist, and an open-seat request.",
  },
  stickers: {
    path: "/assets/fnf-degen-stickers.png",
    src: "/assets/fnf-degen-stickers.png",
    w: 1942,
    h: 809,
    alt: "A scanned sticker sheet of eight original hand-drawn degen monster mascots.",
  },
  navbar: {
    path: "/assets/fnf-navbar-strip-tight.png",
    src: "/assets/fnf-navbar-strip-tight.png",
    w: 1983,
    h: 422,
    alt: "A wide torn-paper strip with original degen mascot stickers and abstract chart scribbles.",
  },
  floorPaper: {
    path: "/assets/fnf-crew-floor-paper.png",
    src: "/assets/fnf-crew-floor-paper.png",
    w: 887,
    h: 1774,
    alt: "A vertical torn-paper memecoin collage with ciel blue tape, chart scraps, and handmade monster doodles.",
  },
};

export const VIDEO = {
  hero: "/assets/fnf-hero-ambient.mp4",
  process: "/assets/fnf-process-ambient.mp4",
  wallet: "/assets/fnf-wallet-ambient.mp4",
  moneyRoom: "/assets/fnf-money-room-720.mp4",
  floor: "/assets/fnf-floor-cockpit-720.mp4",
  nav: "/assets/fnf-nav-strip-720.mp4",
  ritual: "/assets/fnf-ritual-720.mp4",
  trust: "/assets/fnf-trust-720.mp4",
  quoteRoom: "/assets/fnf-quote-room-720.mp4",
  stepTrade: "/assets/fnf-step-trade-720.mp4",
  stepCrews: "/assets/fnf-step-crews-720.mp4",
  stepWeek: "/assets/fnf-step-week-720.mp4",
  walletProof: "/assets/fnf-card-wallet-proof-720.mp4",
  hardCap: "/assets/fnf-card-eight-seats-720.mp4",
  neverShip: "/assets/fnf-card-never-ship-720.mp4",
  reportFreeze: "/assets/fnf-card-report-freeze-720.mp4",
  quoteRasmr: "/assets/fnf-quote-rasmr-720.mp4",
  quoteTrencher: "/assets/fnf-quote-trencher-720.mp4",
  footerRoom: "/assets/fnf-footer-room-720.mp4",
};

export const UI_ART = {
  hero: "/assets/fnf-riso-hero-v2.png",
  floor: "/assets/fnf-riso-floor-v2.png",
  match: "/assets/fnf-riso-match-v2.png",
  trial: "/assets/fnf-riso-trial-v2.png",
  wallet: "/assets/fnf-riso-wallet-v2.png",
  social: "/assets/fnf-riso-social-v2.png",
  world: "/assets/fnf-riso-world-v2.png",
};

export const UI_VIDEO = {
  hero: "/assets/fnf-riso-hero-480.mp4",
  floor: "/assets/fnf-riso-floor-480.mp4",
  stepTrade: "/assets/fnf-riso-step-trade-480.mp4",
  stepCrews: "/assets/fnf-riso-step-crews-480.mp4",
  stepWeek: "/assets/fnf-riso-step-week-480.mp4",
  walletProof: "/assets/fnf-riso-wallet-proof-480.mp4",
  hardCap: "/assets/fnf-riso-hard-cap-480.mp4",
  neverShip: "/assets/fnf-riso-never-ship-480.mp4",
};

export const FILTERS = [
  {
    id: "trading",
    name: "Trading",
    options: ["Memecoins", "Perps", "Day trading"],
  },
  {
    id: "lang",
    name: "Language",
    options: ["English", "Espanol", "Francais", "Turkce", "Bahasa"],
  },
  {
    id: "hours",
    name: "Hours",
    options: ["Asia", "Europe", "Americas", "Around the clock"],
  },
  {
    id: "voice",
    name: "Room",
    options: ["Voice daily", "Voice sometimes", "Text only"],
  },
];

export const CREWS = [
  {
    id: "night-shift",
    name: "Night Shift",
    thesis:
      "Fresh pools after the New York close. Every call ships with a contract and an exit.",
    trading: "Memecoins",
    lang: "English",
    hours: "Americas",
    voice: "Voice daily",
    members: 7,
    seats: 8,
    live: 4,
    age: "11 weeks together",
    track: "Wallets public since week one",
    access: "One question",
    lead: { name: "Marisol Devane", handle: "marisolonchain" },
  },
  {
    id: "frogwater",
    name: "Frogwater",
    thesis:
      "Slow entries on small caps. Liquidity, holder spread and an invalidation, or it does not get posted.",
    trading: "Memecoins",
    lang: "English",
    hours: "Europe",
    voice: "Voice sometimes",
    members: 6,
    seats: 8,
    live: 2,
    age: "5 months together",
    track: "Call history open to members",
    access: "One question",
    lead: { name: "Teodor Vasilj", handle: "teovasilj" },
  },
  {
    id: "second-wave",
    name: "Second Wave",
    thesis:
      "Abandoned tickers with a community still awake. We read the ownership change before the chart.",
    trading: "Memecoins",
    lang: "English",
    hours: "Around the clock",
    voice: "Voice daily",
    members: 7,
    seats: 8,
    live: 5,
    age: "3 months together",
    track: "Six theses running",
    access: "Invite review",
    lead: { name: "Amaka Oyelaran", handle: "amakaoye" },
  },
  {
    id: "salt-flats",
    name: "Salt Flats",
    thesis:
      "One position at a time, held for weeks. Nobody here is watching a five minute candle.",
    trading: "Perps",
    lang: "English",
    hours: "Americas",
    voice: "Text only",
    members: 5,
    seats: 8,
    live: 1,
    age: "8 months together",
    track: "Average hold 19 days",
    access: "Open",
    lead: { name: "Ruthie Kohler", handle: "ruthiekohler" },
  },
  {
    id: "la-tarde",
    name: "La Tarde",
    thesis:
      "Spanish speaking room, afternoons in Madrid. Charts out loud, no signal spam.",
    trading: "Memecoins",
    lang: "Espanol",
    hours: "Europe",
    voice: "Voice daily",
    members: 8,
    seats: 8,
    live: 3,
    age: "14 weeks together",
    track: "Wallets public since week one",
    access: "Waitlist",
    lead: { name: "Iker Balaguer", handle: "ikerbalaguer" },
  },
  {
    id: "paper-route",
    name: "Paper Route",
    thesis:
      "Everyone starts with a paper book for two weeks. Post the sheet, then post the trade.",
    trading: "Day trading",
    lang: "English",
    hours: "Around the clock",
    voice: "Voice sometimes",
    members: 4,
    seats: 8,
    live: 2,
    age: "6 weeks together",
    track: "Beginners welcome, no fee",
    access: "Open",
    lead: { name: "Deshaun Priolo", handle: "deshaunp" },
  },
  {
    id: "nine-lives",
    name: "Nine Lives",
    thesis:
      "Launch snipes with hard rules. Two misses in a row and you sit out the week.",
    trading: "Memecoins",
    lang: "English",
    hours: "Asia",
    voice: "Voice daily",
    members: 6,
    seats: 8,
    live: 6,
    age: "9 weeks together",
    track: "Rules pinned and enforced",
    access: "Invite review",
    lead: { name: "Wen Jia Loh", handle: "wenjialoh" },
  },
  {
    id: "kervan",
    name: "Kervan",
    thesis:
      "Turkish room built on one weekly thesis. We argue it on Sunday and trade it all week.",
    trading: "Perps",
    lang: "Turkce",
    hours: "Europe",
    voice: "Voice sometimes",
    members: 7,
    seats: 8,
    live: 1,
    age: "4 months together",
    track: "One thesis a week, written down",
    access: "One question",
    lead: { name: "Deniz Akaydin", handle: "denizakaydin" },
  },
  {
    id: "warung",
    name: "Warung",
    thesis:
      "Jakarta hours, small size, long conversations. Nobody is trying to sell you a course.",
    trading: "Day trading",
    lang: "Bahasa",
    hours: "Asia",
    voice: "Text only",
    members: 5,
    seats: 8,
    live: 2,
    age: "7 weeks together",
    track: "Call history open to members",
    access: "Open",
    lead: { name: "Rangga Setiawan", handle: "ranggaseti" },
  },
  {
    id: "les-halles",
    name: "Les Halles",
    thesis:
      "French room for mid caps only. If it launched today it is not on the table.",
    trading: "Perps",
    lang: "Francais",
    hours: "Europe",
    voice: "Voice sometimes",
    members: 6,
    seats: 8,
    live: 0,
    age: "6 months together",
    track: "Average hold 26 days",
    access: "Waitlist",
    lead: { name: "Camille Rouvier", handle: "camillerouvier" },
  },
  {
    id: "cold-open",
    name: "Cold Open",
    thesis:
      "Asia morning rotation. Two hours of voice, then everyone goes back to a day job.",
    trading: "Day trading",
    lang: "English",
    hours: "Asia",
    voice: "Voice daily",
    members: 8,
    seats: 8,
    live: 4,
    age: "12 weeks together",
    track: "Wallets public since week one",
    access: "Waitlist",
    lead: { name: "Hina Matsuura", handle: "hinamatsuura" },
  },
  {
    id: "the-bakery",
    name: "The Bakery",
    thesis:
      "Launch snipes on a shared checklist. Contract, mint authority, top ten holders, then size.",
    trading: "Memecoins",
    lang: "English",
    hours: "Around the clock",
    voice: "Voice daily",
    members: 7,
    seats: 8,
    live: 7,
    age: "5 months together",
    track: "Checklist pinned and enforced",
    access: "Invite review",
    lead: { name: "Oskar Lindqvist", handle: "oskarlindq" },
  },
];

export const STEPS = [
  {
    title: "Say how you actually trade",
    body: "Four answers. Trading, language, hours, and whether you want a voice room or a quiet one. No resume, no track record required.",
    image: UI_ART.match,
    video: UI_VIDEO.stepTrade,
  },
  {
    title: "Meet three crews, not three hundred",
    body: "FNF shortlists rooms that already trade the way you do and still have a seat open. You read the thesis before anyone reads your wallet.",
    image: UI_ART.floor,
    video: UI_VIDEO.stepCrews,
  },
  {
    title: "Request the open seat",
    body: "The room lead gets your trading profile. You both decide whether the fit is right, then the room opens.",
    image: UI_ART.trial,
    video: UI_VIDEO.stepWeek,
  },
];
