/* ---------------------------------------------------------------
   Image slots.
   Each entry has the final path the site should ship with and a
   temporary source. Drop the real file at `path`, then flip `src`
   to that path. Nothing else needs to change.
--------------------------------------------------------------- */
export const IMG = {
  hero: {
    path: "/assets/fnf-degen-hero.png",
    src: "/assets/fnf-degen-hero.png",
    w: 1672,
    h: 941,
    alt: "A chaotic late-night trading crew around a laptop, surrounded by ripped paper and original memecoin stickers.",
  },
  desk: {
    path: "/assets/fnf-degen-board.png",
    src: "/assets/fnf-degen-board.png",
    w: 1448,
    h: 1086,
    alt: "A messy memecoin research wall covered with torn screenshots, charts, tape, and original monster doodles.",
  },
  hands: {
    path: "/assets/fnf-degen-wallet.png",
    src: "/assets/fnf-degen-wallet.png",
    w: 1448,
    h: 1086,
    alt: "A phone with blurred wallet history held above a dirty table of receipts, tape, and memecoin sketches.",
  },
  walk: {
    path: "/assets/fnf-degen-hero.png",
    src: "/assets/fnf-degen-hero.png",
    w: 1672,
    h: 941,
    alt: "A late-night memecoin crew watching charts together in a messy bedroom.",
  },
  ledger: {
    path: "/assets/fnf-degen-board.png",
    src: "/assets/fnf-degen-board.png",
    w: 1448,
    h: 1086,
    alt: "A torn-paper trading evidence board with abstract charts, receipts, and original degen mascot stickers.",
  },
  process: {
    path: "/assets/fnf-degen-process.png",
    src: "/assets/fnf-degen-process.png",
    w: 1672,
    h: 941,
    alt: "A ripped-paper triptych showing a preferences card, a crew chat invite, and a trial week receipt pile.",
  },
  stickers: {
    path: "/assets/fnf-degen-stickers.png",
    src: "/assets/fnf-degen-stickers.png",
    w: 1942,
    h: 809,
    alt: "A scanned sticker sheet of eight original hand-drawn degen monster mascots.",
  },
  navbar: {
    path: "/assets/fnf-navbar-strip-tight.png",
    src: "/assets/fnf-navbar-strip-tight.png",
    w: 1983,
    h: 422,
    alt: "A wide torn-paper strip with original degen mascot stickers and abstract chart scribbles.",
  },
  floorPaper: {
    path: "/assets/fnf-crew-floor-paper.png",
    src: "/assets/fnf-crew-floor-paper.png",
    w: 887,
    h: 1774,
    alt: "A vertical torn-paper memecoin collage with ciel blue tape, chart scraps, and handmade monster doodles.",
  },
};

export const FILTERS = [
  {
    id: "style",
    name: "Style",
    options: ["Momentum", "Research", "Takeover", "Snipe", "Hold"],
  },
  {
    id: "cap",
    name: "Market cap",
    options: ["Under 100k", "100k to 1M", "1M to 10M", "Over 10M"],
  },
  {
    id: "lang",
    name: "Language",
    options: ["English", "Espanol", "Francais", "Turkce", "Bahasa"],
  },
  {
    id: "hours",
    name: "Hours",
    options: ["Asia", "Europe", "Americas", "Around the clock"],
  },
  {
    id: "voice",
    name: "Room",
    options: ["Voice daily", "Voice sometimes", "Text only"],
  },
];

export const CREWS = [
  {
    id: "night-shift",
    name: "Night Shift",
    thesis:
      "Fresh pools after the New York close. Every call ships with a contract and an exit.",
    style: "Momentum",
    cap: "Under 100k",
    lang: "English",
    hours: "Americas",
    voice: "Voice daily",
    members: 7,
    seats: 8,
    live: 4,
    age: "11 weeks together",
    track: "Wallets public since week one",
    access: "One question",
    lead: { name: "Marisol Devane", handle: "marisolonchain" },
  },
  {
    id: "frogwater",
    name: "Frogwater",
    thesis:
      "Slow entries on small caps. Liquidity, holder spread and an invalidation, or it does not get posted.",
    style: "Research",
    cap: "100k to 1M",
    lang: "English",
    hours: "Europe",
    voice: "Voice sometimes",
    members: 6,
    seats: 8,
    live: 2,
    age: "5 months together",
    track: "Call history open to members",
    access: "One question",
    lead: { name: "Teodor Vasilj", handle: "teovasilj" },
  },
  {
    id: "second-wave",
    name: "Second Wave",
    thesis:
      "Abandoned tickers with a community still awake. We read the ownership change before the chart.",
    style: "Takeover",
    cap: "Under 100k",
    lang: "English",
    hours: "Around the clock",
    voice: "Voice daily",
    members: 7,
    seats: 8,
    live: 5,
    age: "3 months together",
    track: "Six theses running",
    access: "Invite review",
    lead: { name: "Amaka Oyelaran", handle: "amakaoye" },
  },
  {
    id: "salt-flats",
    name: "Salt Flats",
    thesis:
      "One position at a time, held for weeks. Nobody here is watching a five minute candle.",
    style: "Hold",
    cap: "1M to 10M",
    lang: "English",
    hours: "Americas",
    voice: "Text only",
    members: 5,
    seats: 8,
    live: 1,
    age: "8 months together",
    track: "Average hold 19 days",
    access: "Open",
    lead: { name: "Ruthie Kohler", handle: "ruthiekohler" },
  },
  {
    id: "la-tarde",
    name: "La Tarde",
    thesis:
      "Spanish speaking room, afternoons in Madrid. Charts out loud, no signal spam.",
    style: "Momentum",
    cap: "100k to 1M",
    lang: "Espanol",
    hours: "Europe",
    voice: "Voice daily",
    members: 8,
    seats: 8,
    live: 3,
    age: "14 weeks together",
    track: "Wallets public since week one",
    access: "Waitlist",
    lead: { name: "Iker Balaguer", handle: "ikerbalaguer" },
  },
  {
    id: "paper-route",
    name: "Paper Route",
    thesis:
      "Everyone starts with a paper book for two weeks. Post the sheet, then post the trade.",
    style: "Research",
    cap: "Under 100k",
    lang: "English",
    hours: "Around the clock",
    voice: "Voice sometimes",
    members: 4,
    seats: 8,
    live: 2,
    age: "6 weeks together",
    track: "Beginners welcome, no fee",
    access: "Open",
    lead: { name: "Deshaun Priolo", handle: "deshaunp" },
  },
  {
    id: "nine-lives",
    name: "Nine Lives",
    thesis:
      "Launch snipes with hard rules. Two misses in a row and you sit out the week.",
    style: "Snipe",
    cap: "Under 100k",
    lang: "English",
    hours: "Asia",
    voice: "Voice daily",
    members: 6,
    seats: 8,
    live: 6,
    age: "9 weeks together",
    track: "Rules pinned and enforced",
    access: "Invite review",
    lead: { name: "Wen Jia Loh", handle: "wenjialoh" },
  },
  {
    id: "kervan",
    name: "Kervan",
    thesis:
      "Turkish room built on one weekly thesis. We argue it on Sunday and trade it all week.",
    style: "Hold",
    cap: "1M to 10M",
    lang: "Turkce",
    hours: "Europe",
    voice: "Voice sometimes",
    members: 7,
    seats: 8,
    live: 1,
    age: "4 months together",
    track: "One thesis a week, written down",
    access: "One question",
    lead: { name: "Deniz Akaydin", handle: "denizakaydin" },
  },
  {
    id: "warung",
    name: "Warung",
    thesis:
      "Jakarta hours, small size, long conversations. Nobody is trying to sell you a course.",
    style: "Research",
    cap: "100k to 1M",
    lang: "Bahasa",
    hours: "Asia",
    voice: "Text only",
    members: 5,
    seats: 8,
    live: 2,
    age: "7 weeks together",
    track: "Call history open to members",
    access: "Open",
    lead: { name: "Rangga Setiawan", handle: "ranggaseti" },
  },
  {
    id: "les-halles",
    name: "Les Halles",
    thesis:
      "French room for mid caps only. If it launched today it is not on the table.",
    style: "Hold",
    cap: "Over 10M",
    lang: "Francais",
    hours: "Europe",
    voice: "Voice sometimes",
    members: 6,
    seats: 8,
    live: 0,
    age: "6 months together",
    track: "Average hold 26 days",
    access: "Waitlist",
    lead: { name: "Camille Rouvier", handle: "camillerouvier" },
  },
  {
    id: "cold-open",
    name: "Cold Open",
    thesis:
      "Asia morning rotation. Two hours of voice, then everyone goes back to a day job.",
    style: "Momentum",
    cap: "100k to 1M",
    lang: "English",
    hours: "Asia",
    voice: "Voice daily",
    members: 8,
    seats: 8,
    live: 4,
    age: "12 weeks together",
    track: "Wallets public since week one",
    access: "Waitlist",
    lead: { name: "Hina Matsuura", handle: "hinamatsuura" },
  },
  {
    id: "the-bakery",
    name: "The Bakery",
    thesis:
      "Launch snipes on a shared checklist. Contract, mint authority, top ten holders, then size.",
    style: "Snipe",
    cap: "Under 100k",
    lang: "English",
    hours: "Around the clock",
    voice: "Voice daily",
    members: 7,
    seats: 8,
    live: 7,
    age: "5 months together",
    track: "Checklist pinned and enforced",
    access: "Invite review",
    lead: { name: "Oskar Lindqvist", handle: "oskarlindq" },
  },
];

export const STEPS = [
  {
    title: "Say how you actually trade",
    body: "Five answers. Style, size, language, hours, and whether you want a voice room or a quiet one. No resume, no track record required.",
    image: IMG.process,
  },
  {
    title: "Meet three crews, not three hundred",
    body: "FNF shortlists rooms that already trade the way you do and still have a seat open. You read the thesis before anyone reads your wallet.",
    image: IMG.hands,
  },
  {
    title: "Sit in for a week",
    body: "Every crew runs a trial week. You watch the room, the room watches you, and either side can walk away without a conversation.",
    image: IMG.ledger,
  },
];
